"""WebSocket client utilities for connecting to Soothe daemon.

This package provides the client-side WebSocket connection,
session management, and daemon communication helpers.
"""

from soothe_sdk.client.helpers import (
    check_daemon_status,
    fetch_config_section,
    fetch_skills_catalog,
    is_daemon_live,
    request_daemon_shutdown,
    websocket_url_from_config,
)
from soothe_sdk.client.intent_hints import (
    EMBED,
    IMAGE_TO_TEXT,
    OCR,
    TEXT_COMPLETION,
    validate_loop_input_intent_hint,
)

# Client-side params validation models (RFC-450 §6.5)
from soothe_sdk.client.protocol_params import (
    AuthParams,
    AuthRefreshParams,
    AutopilotSubscribeParams,
    ConfigGetParams,
    DaemonShutdownParams,
    DaemonStatusParams,
    DisconnectParams,
    InvokeSkillParams,
    JobCancelParams,
    JobCreateParams,
    JobDagParams,
    JobGuidanceParams,
    JobPauseParams,
    JobResumeParams,
    JobStatusParams,
    LoopCardsFetchParams,
    LoopDeleteParams,
    LoopDetachParams,
    LoopGetParams,
    LoopInputParams,
    LoopListParams,
    LoopMessagesParams,
    LoopNewParams,
    LoopPruneParams,
    LoopReattachParams,
    LoopStateGetParams,
    LoopStateUpdateParams,
    LoopTreeParams,
    McpStatusParams,
    ModelsListParams,
    RpcCommandParams,
    SkillsListParams,
    SlashCommandParams,
    SubscribeParams,
)
from soothe_sdk.client.session import (
    bootstrap_loop_session,
    connect_websocket_with_retries,
)
from soothe_sdk.client.websocket import WebSocketClient
from soothe_sdk.client.wire import (
    DEFAULT_PROTO,
    BatchRequest,
    BatchRequestEnvelope,
    BatchResponseEnvelope,
    ConnectionAckEnvelope,
    ConnectionAckResult,
    ConnectionInitEnvelope,
    ConnectionInitParams,
    ErrorEnvelope,
    MessageType,
    PingEnvelope,
    PongEnvelope,
    ProtocolError,
    ResponseEnvelope,
    WireEnvelope,
    decode_envelope,
    encode_envelope,
    envelope_langchain_message_dict,
    messages_from_wire_dicts,
)
from soothe_sdk.client.ws_command_client import (
    SyncWsCommandClient,
    WsCommandClient,
    async_ws_command_client_from_config,
    ws_command_client_from_config,
)
from soothe_sdk.core.types import VerbosityLevel

__all__ = [
    "WebSocketClient",
    "VerbosityLevel",
    "WsCommandClient",
    "SyncWsCommandClient",
    "ws_command_client_from_config",
    "async_ws_command_client_from_config",
    "bootstrap_loop_session",
    "connect_websocket_with_retries",
    "websocket_url_from_config",
    "check_daemon_status",
    "is_daemon_live",
    "request_daemon_shutdown",
    "fetch_skills_catalog",
    "fetch_config_section",
    "TEXT_COMPLETION",
    "IMAGE_TO_TEXT",
    "OCR",
    "EMBED",
    "validate_loop_input_intent_hint",
    "envelope_langchain_message_dict",
    "messages_from_wire_dicts",
    # Protocol-1 wire envelope models (RFC-450 §5, IG-522 Phase 1)
    "DEFAULT_PROTO",
    "MessageType",
    "WireEnvelope",
    "ResponseEnvelope",
    "ErrorEnvelope",
    "ConnectionInitParams",
    "ConnectionAckResult",
    "ConnectionInitEnvelope",
    "ConnectionAckEnvelope",
    "PingEnvelope",
    "PongEnvelope",
    "ProtocolError",
    "BatchRequest",
    "BatchRequestEnvelope",
    "BatchResponseEnvelope",
    "encode_envelope",
    "decode_envelope",
    # Client-side params validation models (RFC-450 §6.5)
    "LoopGetParams",
    "LoopListParams",
    "LoopTreeParams",
    "LoopPruneParams",
    "LoopDeleteParams",
    "LoopNewParams",
    "LoopReattachParams",
    "LoopInputParams",
    "LoopMessagesParams",
    "LoopStateGetParams",
    "LoopStateUpdateParams",
    "LoopCardsFetchParams",
    "LoopDetachParams",
    "SubscribeParams",
    "AutopilotSubscribeParams",
    "JobCreateParams",
    "JobStatusParams",
    "JobPauseParams",
    "JobResumeParams",
    "JobCancelParams",
    "JobDagParams",
    "JobGuidanceParams",
    "DaemonStatusParams",
    "DaemonShutdownParams",
    "ConfigGetParams",
    "SkillsListParams",
    "ModelsListParams",
    "InvokeSkillParams",
    "McpStatusParams",
    "AuthParams",
    "AuthRefreshParams",
    "SlashCommandParams",
    "RpcCommandParams",
    "DisconnectParams",
]
