"""Declarative configuration for Soothe agents.

All public names are re-exported here so that ``from soothe.config import X``
continues to work after the module was split into a package.
"""

from soothe.config.constants import (
    DEFAULT_AGENT_LOOP_MAX_ITERATIONS,
    DEFAULT_AUTONOMOUS_MAX_ITERATIONS,
    DEFAULT_EXECUTE_TIMEOUT,
    DEFAULT_PRIOR_CONVERSATION_LIMIT,
    DEFAULT_RECENT_MESSAGES_FOR_CLASSIFY_LIMIT,
    MAX_CONSECUTIVE_EMPTY_TOOL_CALLS,
    MAX_EVIDENCE_STRING_LENGTH,
)
from soothe.config.env import (
    _ENV_VAR_RE,
    SOOTHE_HOME,
    _resolve_env,
    _resolve_provider_env,
)
from soothe.config.models import (
    AgentConfig,
    AgentLoopConfig,
    AutonomousConfig,
    ComplexityThresholds,
    ConsoleLoggingConfig,
    DurabilityProtocolConfig,
    FileLoggingConfig,
    HttpRequestsToolsConfig,
    InfrastructureLimitsConfig,
    MCPServerConfig,
    MemUConfig,
    ModelProviderConfig,
    ModelRouter,
    ObservabilityConfig,
    PersistenceConfig,
    PlannerProtocolConfig,
    PlanPromptLedgerConfig,
    PolicyProtocolConfig,
    ProtocolsConfig,
    RecoveryConfig,
    SecurityConfig,
    SubagentConfig,
    ThreadLoggingConfig,
    ToolConfig,
    ToolsConfig,
    VectorStoreProviderConfig,
    VectorStoreRouter,
    WebSearchConfig,
)
from soothe.config.settings import SootheConfig
from soothe.foundation.loop.prompts import (
    _DEFAULT_SYSTEM_PROMPT,
    _MEDIUM_SYSTEM_PROMPT,
    _SIMPLE_SYSTEM_PROMPT,
    _TOOL_ORCHESTRATION_GUIDE,
)

__all__ = [
    "DEFAULT_AGENT_LOOP_MAX_ITERATIONS",
    "DEFAULT_AUTONOMOUS_MAX_ITERATIONS",
    "DEFAULT_EXECUTE_TIMEOUT",
    "DEFAULT_PRIOR_CONVERSATION_LIMIT",
    "DEFAULT_RECENT_MESSAGES_FOR_CLASSIFY_LIMIT",
    "MAX_CONSECUTIVE_EMPTY_TOOL_CALLS",
    "MAX_EVIDENCE_STRING_LENGTH",
    "SOOTHE_HOME",
    "_DEFAULT_SYSTEM_PROMPT",
    "_ENV_VAR_RE",
    "_MEDIUM_SYSTEM_PROMPT",
    "_SIMPLE_SYSTEM_PROMPT",
    "_TOOL_ORCHESTRATION_GUIDE",
    "AgentConfig",
    "AgentLoopConfig",
    "AutonomousConfig",
    "ComplexityThresholds",
    "ConsoleLoggingConfig",
    "DurabilityProtocolConfig",
    "FileLoggingConfig",
    "HttpRequestsToolsConfig",
    "InfrastructureLimitsConfig",
    "MCPServerConfig",
    "MemUConfig",
    "ModelProviderConfig",
    "ModelRouter",
    "ObservabilityConfig",
    "PersistenceConfig",
    "PlanPromptLedgerConfig",
    "PlannerProtocolConfig",
    "PolicyProtocolConfig",
    "ProtocolsConfig",
    "RecoveryConfig",
    "SecurityConfig",
    "SootheConfig",
    "SubagentConfig",
    "ThreadLoggingConfig",
    "ToolConfig",
    "ToolsConfig",
    "VectorStoreProviderConfig",
    "VectorStoreRouter",
    "WebSearchConfig",
    "_resolve_env",
    "_resolve_provider_env",
]
