"""Daemon-owned wire event type string constants (centralized)."""

from soothe_daemon.events.constants import (
    CHANNEL_MESSAGE_RECEIVED,
    OUTPUT_PROGRESS,
    OUTPUT_REASONING,
    OUTPUT_TEXT_COMPLETE,
    OUTPUT_TEXT_DELTA,
    OUTPUT_TEXT_END,
    OUTPUT_UI_RENDER,
    SKILLIFY_INDEX_FAILED,
    SKILLIFY_INDEX_STARTED,
    SKILLIFY_INDEX_UNCHANGED,
    SKILLIFY_INDEX_UPDATED,
    SKILLIFY_RETRIEVE_COMPLETED,
)

__all__ = [
    "CHANNEL_MESSAGE_RECEIVED",
    "OUTPUT_PROGRESS",
    "OUTPUT_REASONING",
    "OUTPUT_TEXT_COMPLETE",
    "OUTPUT_TEXT_DELTA",
    "OUTPUT_TEXT_END",
    "OUTPUT_UI_RENDER",
    "SKILLIFY_INDEX_FAILED",
    "SKILLIFY_INDEX_STARTED",
    "SKILLIFY_INDEX_UNCHANGED",
    "SKILLIFY_INDEX_UPDATED",
    "SKILLIFY_RETRIEVE_COMPLETED",
]
