#!/usr/bin/env bash
#
# sync_wiki_changelog.sh — Publish root CHANGELOG.md into the gh-pages wiki.
#
# Source of truth: repository root CHANGELOG.md
# Generated page:  docs/wiki/changelog.md (Just the Docs permalink /changelog/)
#
# Usage:
#   ./scripts/sync_wiki_changelog.sh           # rewrite wiki page
#   ./scripts/sync_wiki_changelog.sh --check   # exit 1 if wiki page is stale
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${ROOT}/CHANGELOG.md"
DST="${ROOT}/docs/wiki/changelog.md"
TMP="$(mktemp)"

cleanup() { rm -f "$TMP"; }
trap cleanup EXIT

if [[ ! -f "$SRC" ]]; then
  echo "error: missing ${SRC}" >&2
  exit 1
fi

{
  cat <<'EOF'
---
title: CHANGELOG
layout: default
nav_order: 4
description: >-
  All notable changes to Soothe are documented in this file, following the
  Keep a Changelog format. Generated from the repository root CHANGELOG.md.
permalink: /changelog/
---

<!--
  AUTO-GENERATED from repository root CHANGELOG.md.
  Do not edit this file by hand. Run: ./scripts/sync_wiki_changelog.sh
-->

> **Source of truth:** repository root
> [`CHANGELOG.md`](https://github.com/mirasoth/soothe/blob/main/CHANGELOG.md).
> Per-version API surface diffs:
> **[Versioned Changelogs](../changelogs/)**.

EOF
  cat "$SRC"
  # Guarantee a terminating newline even if CHANGELOG.md lacks one.
  printf '\n'
} >"$TMP"

# Normalize to exactly one trailing newline.
python3 - "$TMP" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8").rstrip() + "\n"
path.write_text(text, encoding="utf-8")
PY

if [[ "${1:-}" == "--check" ]]; then
  if [[ ! -f "$DST" ]]; then
    echo "error: missing ${DST} (run ./scripts/sync_wiki_changelog.sh)" >&2
    exit 1
  fi
  if ! diff -q "$DST" "$TMP" >/dev/null; then
    echo "error: docs/wiki/changelog.md is out of sync with CHANGELOG.md" >&2
    echo "       run: ./scripts/sync_wiki_changelog.sh" >&2
    diff -u "$DST" "$TMP" || true
    exit 1
  fi
  echo "ok: docs/wiki/changelog.md matches CHANGELOG.md"
  exit 0
fi

cp "$TMP" "$DST"
echo "synced: CHANGELOG.md → docs/wiki/changelog.md"
